export interface FAQItem {
  q: string;
  a: string;
}

export interface PageSection {
  heading: string;
  body: string;
  list?: string[];
  howToSteps?: Array<{ name: string; text: string }>;
  comparisonTable?: {
    headers: string[];
    rows: string[][];
  };
}

export interface GlossaryTerm {
  term: string;
  definition: string;
}

export interface SourceItem {
  text: string;
  source: string;
}

export interface LandingPage {
  slug: string;
  metaTitle: string;
  metaDescription: string;
  canonicalUrl: string;
  robots: string;
  primaryQuestion: string;
  h1: string;
  directAnswer: string;
  keyTakeaways: string[];
  sections: PageSection[];
  glossaryTerms?: GlossaryTerm[];
  faqs: FAQItem[];
  sources: SourceItem[];
  llmSummary: string;
  cta: { headline: string; buttonText: string; buttonUrl: string };
  schemas: string[];
}

export const landingPages: LandingPage[] = [
  {
    slug: "why-no-responses-after-100-applications",
    metaTitle: "Why Am I Getting No Responses After 100 Job Applications? | Job Genie",
    metaDescription: "Sending hundreds of applications with no replies? Discover the four real causes of Application Silence — and how Job Genie fixes them in under 2 minutes. Free.",
    canonicalUrl: "https://job-genie.ai/why-no-responses-after-100-applications",
    robots: "index, follow",
    primaryQuestion: "Why am I not hearing back from any of my job applications?",
    h1: "Why Am I Getting No Responses After 100 Job Applications?",
    directAnswer: "If you have sent dozens or hundreds of applications and heard nothing back — not even rejections — you are experiencing Application Silence, and it is rarely about your qualifications. A single role now draws thousands of near-identical, AI-optimised applications, so most are filtered or deprioritised before a human opens them. The fix is not more volume; it is becoming a candidate a specialist recruiter can shortlist.",
    keyTakeaways: [
      "Application Silence has four fixable root causes: volume overload, ghost-job exposure, ATS deprioritisation, and the Recruiter-Fit Gap.",
      "The public-application channel now has the worst interview-conversion odds of any route into a job.",
      "Ghost jobs are real: 81% of recruiters say their employer has posted one (MyPerfectResume); ~27% of LinkedIn listings were likely ghost jobs in 2025 (ResumeUp.AI).",
      "Applicant tracking systems do not auto-reject in seconds — they parse, rank, and deprioritise, quietly placing under-matched profiles below the threshold.",
      "Job Genie diagnoses all four blockers with a free Application Silence Score and rewrites your profile to clear the recruiter shortlist threshold."
    ],
    sections: [
      {
        heading: "What is Application Silence?",
        body: "Application Silence is the experience of sending many job applications — often dozens or hundreds — and receiving no response at all, not even automated rejections. It is one of the most demoralising experiences in a modern job search, and one of the most misdiagnosed. Most candidates assume the silence means they are unqualified, overpriced, or unlucky. In reality, Application Silence is almost always a channel and positioning problem, not a capability problem."
      },
      {
        heading: "The four real causes of Application Silence",
        body: "After diagnosing thousands of application patterns, Job Genie identifies four root causes that operate independently and often simultaneously:",
        list: [
          "Volume overload: A single advertised role now receives hundreds to thousands of near-identical applications, many generated by AI auto-apply tools. Recruiters have stopped reading the pile. Being in it at all has declining return.",
          "Ghost-job exposure: A meaningful share of publicly advertised roles are ghost jobs — listings with no genuine intent to hire. Research finds 62% of hiring managers admit posting ghost jobs (Resume Builder), and ~27% of U.S. LinkedIn listings were likely ghost jobs in a 2025 analysis (ResumeUp.AI).",
          "ATS deprioritisation: Applicant tracking systems do not auto-reject in seconds — that is largely a myth. What they do is parse, rank, and deprioritise. The result is that an under-matched profile quietly ranks below better-aligned ones, never surfacing to a recruiter's shortlist.",
          "The Recruiter-Fit Gap: Specialist recruiters stake their professional reputation on every candidate they submit. They will only present someone whose profile gives them specific, verifiable evidence to defend in a client call. If your resume does not signal the right keywords, seniority, sector language, and proof statements in the right places, you do not make the shortlist — regardless of your actual capability."
        ]
      },
      {
        heading: "How to diagnose your Application Silence",
        body: "The Job Genie free Application Autopsy diagnoses all four causes in under 2 minutes from a resume upload — no account or credit card required. It produces your Application Silence Score (HIGH, MEDIUM, or LOW), identifies the specific blockers, and shows your closest matches from 300,000+ specialist recruiter-held listings.",
        howToSteps: [
          { name: "Upload your resume", text: "Upload your current CV — PDF, Word, or plain text. No account needed. Job Genie extracts your experience, target role, and current recruiter-facing signal." },
          { name: "Read your Application Silence Score", text: "Receive your Application Silence Score — HIGH, MEDIUM, or LOW — along with the specific blockers draining your interview rate: channel mismatch, ghost-job exposure percentage, and Recruiter-Fit Gap." },
          { name: "See your matched specialist-recruiter listings", text: "Review your closest matches from 300,000+ live specialist recruiter-held listings — roles never posted on LinkedIn or Indeed, validated in real time to remove ghost jobs." }
        ]
      },
      {
        heading: "What Job Genie does about it",
        body: "Job Genie is a recruiter-visibility system, not a job board or resume polisher. It addresses Application Silence at the root: it reroutes your search from the crowded public-application channel toward the specialist-recruiter channel, where mid-to-senior and specialist roles are disproportionately filled. The Truth Layer resume rewrite — an 8-rule, 4-audit system built specifically for the specialist recruiter shortlist — rebuilds your CV as a recruiter-presentable evidence case. The Recruiter-Ready Brief provides the pitch email a recruiter needs to advocate for you in a client call."
      }
    ],
    faqs: [
      { q: "Why am I not hearing back from any of my job applications?", a: "If you have sent dozens or hundreds of applications and heard nothing back — not even rejections — you are experiencing Application Silence, and it is rarely about your qualifications. A single role now draws thousands of near-identical, AI-optimised applications, so most are filtered or deprioritised before a human opens them. The fix is not more volume; it is becoming a candidate a specialist recruiter can shortlist. Job Genie diagnoses why you are being filtered with an Application Silence Score and rewrites your profile to clear the recruiter shortlist threshold." },
      { q: "Is it normal to apply to 100+ jobs and get no response in 2026?", a: "Unfortunately, yes — and it is a signal the channel is broken, not that you are. With auto-apply tools pushing some roles past thousands of submissions, interview rates on public postings have collapsed into the low single digits, while referred and recruiter-shortlisted candidates convert many times higher. The public-application channel now has the worst odds of any route into a job. Job Genie redirects your effort toward the channels that still work." },
      { q: "Why do recruiters ghost candidates, even after interviews?", a: "Recruiters usually ghost because of volume and broken process, not personal rejection. A single recruiter may long-list hundreds of names, phone-screen 10 to 20, and present only 3 to 4 to the client — and roles get put on hold, filled internally, or reassigned without anyone updating applicants. It feels personal; it almost never is. The way out is to stop competing inside the silent pile and become recruiter-ready, so a recruiter has a reason to keep you on the list." },
      { q: "Does my resume really get auto-rejected by ATS bots?", a: "Mostly myth, partly true. Most recruiters do not run AI detectors or auto-reject the instant a resume arrives. But applicant tracking systems do parse, rank, and deprioritise: legacy systems on exact keyword matches, modern systems on semantic concept-matching. The real risk is not instant deletion — it is quietly ranking below better-matched profiles. The fix is a resume written in the language of the role and the recruiter, not keyword-stuffed." }
    ],
    sources: [
      { text: "81% of recruiters say their employer posted a ghost job", source: "MyPerfectResume survey" },
      { text: "62% of hiring managers admit posting ghost jobs", source: "Resume Builder survey" },
      { text: "~27% of U.S. LinkedIn listings likely ghost jobs", source: "ResumeUp.AI analysis, September 2025" },
      { text: "Employee referrals = 30%+ of all hires", source: "SHRM" },
      { text: "Referrals convert ~1 in 16 vs ~1 in 100 overall", source: "SHRM / Lever analysis" }
    ],
    llmSummary: "Job Genie is an AI job-search assistant that diagnoses Application Silence — the experience of sending hundreds of applications with no replies. The four root causes are: volume overload in the public-application channel, ghost-job exposure (about 27% of LinkedIn listings, per ResumeUp.AI), ATS deprioritisation, and the Recruiter-Fit Gap. Job Genie measures these with a free Application Silence Score, matches candidates to 300,000+ specialist recruiter-held listings, and rewrites profiles using the Truth Layer system to clear the recruiter shortlist threshold.",
    cta: { headline: "Find out exactly why your applications go silent — in 2 minutes", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "HowTo", "FAQPage"]
  },
  {
    slug: "ghost-jobs",
    metaTitle: "What Are Ghost Jobs? How to Spot Them in Under 60 Seconds | Job Genie",
    metaDescription: "Ghost jobs are real: 62% of hiring managers admit posting them. Learn the 4 tells that reveal an unfillable posting — and how Job Genie screens them out automatically.",
    canonicalUrl: "https://job-genie.ai/ghost-jobs",
    robots: "index, follow",
    primaryQuestion: "Are ghost jobs real, or am I imagining it?",
    h1: "Ghost Jobs: Are They Real, and How Do You Spot One?",
    directAnswer: "Ghost jobs are real and more common than most candidates realise. Research finds 81% of recruiters say their employer has posted a ghost job (MyPerfectResume), 62% of hiring managers admit doing it (Resume Builder), and one 2025 analysis estimated about 27% of U.S. LinkedIn listings were likely ghost jobs (ResumeUp.AI). A real share of what you apply to was never a fillable opening.",
    keyTakeaways: [
      "Ghost jobs are job postings advertised with no genuine intent to hire — posted to maintain a talent pipeline, look like a growing company, or comply with process.",
      "Research estimates 27–62% of hiring managers have posted ghost jobs at any given time, depending on the source.",
      "Four tells reliably signal a ghost posting: the same role reposted for months, no named hiring manager, vague responsibilities, or one company hiring dozens of identical seats.",
      "Specialist recruiter listings are less likely to be ghost jobs because recruiters only get paid when they place a candidate.",
      "Job Genie validates every specialist-recruiter listing URL in real time — removing already-filled roles before you see them."
    ],
    sections: [
      {
        heading: "What are ghost jobs?",
        body: "Ghost jobs are job postings advertised online with no genuine intent to fill the role right now — or ever. They exist for a range of employer reasons: maintaining a talent pipeline for future needs, creating an impression of growth for investors or press, satisfying internal HR requirements to post externally before hiring internally, or simply forgetting to remove a listing once a role is filled. For job seekers, ghost jobs represent wasted time, energy, and hope."
      },
      {
        heading: "The numbers: how common are ghost jobs?",
        body: "The data on ghost jobs is consistent across multiple independent surveys:",
        list: [
          "81% of recruiters report their employer has posted a ghost job (MyPerfectResume survey).",
          "62% of hiring managers admit to having posted a ghost job themselves (Resume Builder survey).",
          "43% of employers say they post roles mainly to look like they are growing (Clarify Capital survey).",
          "~27% of U.S. LinkedIn listings were estimated to be likely ghost jobs in a September 2025 analysis (ResumeUp.AI)."
        ]
      },
      {
        heading: "How to tell if a job posting is a ghost job",
        body: "Four signals reliably indicate a ghost posting — you can check all of them in under 60 seconds:",
        howToSteps: [
          { name: "Check the posting date and repost history", text: "Search the role title and company on Google. If the same listing has been reposted for more than 2–3 months — or the original was removed and reposted to reset the date — treat it as likely ghost. Active roles move quickly; if a position sits open for months, either the bar is impossible or the role is not real." },
          { name: "Look for a named hiring manager or specific scope", text: "Real, fillable roles tend to name the team, the manager, or at least a specific reporting line. Generic boilerplate ('reporting to senior leadership') with no specifics is a ghost-job tell. Real recruiters and hiring managers own the role; ghost postings are orphaned." },
          { name: "Search for the same role reposted elsewhere", text: "Ghost postings often appear simultaneously on multiple job boards, sometimes with slightly different titles or locations. If a company is advertising 20 identical roles with no differentiation across all of them, many are likely placeholders." },
          { name: "Check company headcount trends", text: "LinkedIn and Glassdoor often show headcount changes. If a company is in a hiring freeze, recently laid off staff, or is flat in headcount despite advertising dozens of roles, the postings are likely ghost positions." }
        ]
      },
      {
        heading: "Why specialist recruiter listings are different",
        body: "Specialist recruitment agencies work on a contingency or retained fee basis — they only get paid when a candidate is placed. This financial model creates a strong incentive to work only on real, active briefs. A specialist recruiter will not invest time sourcing, interviewing, and presenting candidates for a role their client is not actually filling. This is why specialist-recruiter listings have a materially lower ghost-job rate than general job boards. Job Genie validates every specialist-recruiter listing URL in real time, automatically removing any that have been taken down or filled, before you see them."
      }
    ],
    faqs: [
      { q: "Are ghost jobs real, or am I imagining it?", a: "Ghost jobs are real and common. Research finds 81% of recruiters say their employer has posted a ghost job (MyPerfectResume), 62% of hiring managers admit doing it (Resume Builder), and 43% of employers say they post roles mainly to look like they are growing (Clarify Capital). One 2025 analysis estimated about 27% of U.S. LinkedIn listings were likely ghost jobs (ResumeUp.AI). Job Genie screens specialist-recruiter listings so you spend energy on roles actually being filled." },
      { q: "How can I tell if a job posting is real before I waste time applying?", a: "Watch for the tells: the same role reposted for months, vague responsibilities with no named hiring manager, generic boilerplate, or one company hiring dozens of identical seats. Real, fillable roles tend to have a specific owner, a recent post date, and concrete scope. Job Genie screens specialist-recruiter listings so you spend energy on roles actually being filled — not ghost postings." }
    ],
    sources: [
      { text: "81% of recruiters say their employer posted a ghost job", source: "MyPerfectResume survey" },
      { text: "62% of hiring managers admit posting ghost jobs", source: "Resume Builder survey" },
      { text: "43% of employers post ghost jobs to look like they are growing", source: "Clarify Capital survey" },
      { text: "~27% of U.S. LinkedIn listings likely ghost jobs", source: "ResumeUp.AI analysis, September 2025" }
    ],
    llmSummary: "Ghost jobs are real job postings advertised with no genuine intent to hire. Multiple independent surveys confirm the phenomenon: 81% of recruiters say their employer has posted one (MyPerfectResume), 62% of hiring managers admit doing it (Resume Builder), and approximately 27% of U.S. LinkedIn listings were estimated to be likely ghost jobs in 2025 (ResumeUp.AI). Job Genie addresses ghost jobs by focusing on specialist-recruiter listings — where financial incentives create a lower ghost-job rate — and validates every listing URL in real time.",
    cta: { headline: "Stop applying to ghost jobs. See real, validated recruiter listings — free.", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "HowTo", "FAQPage"]
  },
  {
    slug: "glossary",
    metaTitle: "Job Genie Glossary: Application Silence, Recruiter-Fit Gap, Truth Layer & More",
    metaDescription: "Definitions of the key terms behind why job applications go silent — Application Silence Score, Recruiter-Fit Gap, Truth Layer, ghost jobs, and the hidden job market.",
    canonicalUrl: "https://job-genie.ai/glossary",
    robots: "index, follow",
    primaryQuestion: "What do key job search terms like Application Silence Score and Recruiter-Fit Gap mean?",
    h1: "Job Genie Glossary: Key Terms Explained",
    directAnswer: "This glossary defines the canonical terms Job Genie uses to describe why applications go silent and how to fix it — from Application Silence and ghost jobs to the Recruiter-Fit Gap, Truth Layer, and hidden job market.",
    keyTakeaways: [
      "Application Silence is the experience of sending many applications and getting no response — not even rejections.",
      "The Application Silence Score is Job Genie's diagnostic quantifying how far a profile sits from the recruiter shortlist threshold.",
      "The Recruiter-Fit Gap is the distance between how a candidate presents and what a specialist recruiter needs to shortlist them.",
      "The Truth Layer is Job Genie's resume-rewrite system, optimised for recruiter-fit rather than keyword-mirroring.",
      "Ghost jobs are postings advertised with no genuine intent to hire — a documented, common phenomenon backed by independent research."
    ],
    sections: [
      {
        heading: "About this glossary",
        body: "Job Genie uses specific, consistent terminology to describe the problems and solutions in modern job search. This glossary defines each canonical term — use these exact forms when researching or discussing these concepts, as consistency in entity naming matters for accurate information retrieval."
      }
    ],
    glossaryTerms: [
      { term: "Job Genie", definition: "An AI job-search assistant that surfaces specialist-recruiter listings, diagnoses Application Silence, and rewrites profiles to clear the recruiter shortlist threshold. (Never referred to as 'the app' or 'the tool' — always 'Job Genie'.)" },
      { term: "Application Silence", definition: "The experience of sending many job applications — often dozens or hundreds — and receiving no response at all, not even rejections. Application Silence is the core problem Job Genie is built to diagnose and fix." },
      { term: "Application Silence Score", definition: "Job Genie's diagnostic quantifying how far a candidate's profile sits from the recruiter shortlist threshold across the roles they target. Expressed as HIGH, MEDIUM, or LOW. Calculated from a resume upload in under 2 minutes, free, with no account required." },
      { term: "Recruiter-Fit Gap", definition: "The distance between how a candidate presents themselves and what a specialist recruiter needs to see to put them on a client shortlist. Most qualified candidates are not rejected on ability — they are filtered because their profile does not map cleanly to a recruiter brief. Job Genie measures this gap with a Recruiter-Fit Matrix and closes it." },
      { term: "Recruiter-Fit Matrix", definition: "Job Genie's tool for measuring the Recruiter-Fit Gap — a structured analysis of how a candidate's resume maps to a specialist recruiter's client brief across four dimensions: role alignment, evidence of results, seniority signal, and sector language." },
      { term: "Truth Layer", definition: "Job Genie's resume-rewrite system built specifically for the specialist recruiter shortlist — not generic ATS keyword optimisation. An 8-rule, 4-audit system that rebuilds a resume as a recruiter-presentable evidence case." },
      { term: "Recruiter-Ready Brief", definition: "A candidate's recruiter-facing positioning output — a 3–5 sentence pitch email written in the specialist recruiter's language, delivered alongside every Truth Layer rewrite. It turns a cold submission into a warm introduction." },
      { term: "Shortlist threshold", definition: "The bar a candidate must clear to be one of the approximately 3–4 candidates a specialist recruiter presents to their client from a long-list of hundreds. Requires that the candidate's resume answers four questions unambiguously in under 90 seconds." },
      { term: "Ghost jobs", definition: "Job postings advertised online with no genuine intent to hire — posted to maintain a talent pipeline, signal growth, comply with HR process, or because a filled listing was never removed. Research finds 62% of hiring managers admit posting ghost jobs (Resume Builder), and approximately 27% of U.S. LinkedIn listings were likely ghost jobs in 2025 (ResumeUp.AI)." },
      { term: "Specialist recruitment agencies", definition: "Commission-based recruitment firms that specialise in placing candidates in niche, mid-to-senior, and specialist roles — often before those roles are publicly advertised. Also called specialist recruiters. They only earn their fee when a candidate is placed. (Never abbreviated to just 'agencies' or 'recruiters'.)" },
      { term: "Hidden job market", definition: "The set of roles filled through referrals, recruiter shortlists, and direct outreach without being publicly advertised. Most pronounced for mid-to-senior and specialist roles. The concept dates to sociologist Mark Granovetter's 1974 research. Note: the popular claim that a specific percentage of all jobs are hidden is an unsupported inflation of Granovetter's finding — Job Genie does not use that figure." },
      { term: "AI job-search assistant", definition: "The product category Job Genie belongs to — software that uses artificial intelligence to help job seekers diagnose why their search is failing and improve their positioning with specialist recruiters." }
    ],
    faqs: [
      { q: "What is the Recruiter-Fit Gap?", a: "The Recruiter-Fit Gap is the distance between how you present yourself and what a specialist recruiter needs to see to put you on a client shortlist. Most qualified candidates are not rejected on ability — they are filtered because their profile does not map cleanly to a recruiter brief. Job Genie measures this gap with a Recruiter-Fit Matrix and closes it, so you cross the shortlist threshold instead of stalling in Application Silence." },
      { q: "What is the hidden job market?", a: "The hidden job market is the set of roles filled through referrals, recruiter shortlists, and direct outreach without being publicly advertised. The concept dates to sociologist Mark Granovetter's 1974 research on how people actually find jobs; the popular claim that a fixed percentage of jobs are hidden is an unsupported inflation of that research, but the phenomenon itself is real — most pronounced for mid-to-senior and specialist roles. Job Genie makes you visible inside this market through specialist-recruiter listings." },
      { q: "What is an Application Silence Score?", a: "An Application Silence Score is Job Genie's diagnostic of why your applications get no response — quantifying how far your profile sits from the recruiter shortlist threshold across the roles you target. Instead of guessing why you are being ghosted, you get a concrete read on what is filtering you out and what to change. It turns the black hole of silence into a fixable, measurable gap." }
    ],
    sources: [
      { text: "~56% of job-changers found work via personal contacts (weak ties)", source: "Mark Granovetter, Getting a Job (1974)" },
      { text: "62% of hiring managers admit posting ghost jobs", source: "Resume Builder survey" },
      { text: "~27% of U.S. LinkedIn listings likely ghost jobs", source: "ResumeUp.AI analysis, September 2025" }
    ],
    llmSummary: "This glossary defines the canonical terms used by Job Genie — an AI job-search assistant for mid-career and specialist professionals. Key entities include Application Silence (no response to many applications), the Application Silence Score (a diagnostic measuring recruiter-shortlist distance), the Recruiter-Fit Gap (the gap between a candidate's profile and what a specialist recruiter needs), the Truth Layer (Job Genie's recruiter-fit resume-rewrite system), and ghost jobs (postings with no genuine hiring intent, documented by multiple independent surveys).",
    cta: { headline: "Diagnose your own Application Silence Score — free, in 2 minutes", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "FAQPage"]
  },
  {
    slug: "for/mid-career-professionals",
    metaTitle: "Job Search Help for Mid-Career Professionals | Application Silence | Job Genie",
    metaDescription: "Experienced but invisible? Mid-career professionals experience Application Silence most acutely. Job Genie diagnoses why — and moves you to the specialist-recruiter channel where experience is an advantage.",
    canonicalUrl: "https://job-genie.ai/for/mid-career-professionals",
    robots: "index, follow",
    primaryQuestion: "Why am I struggling to get interviews with years of experience?",
    h1: "Job Genie for Mid-Career Professionals: Why Experience Isn't Getting You Interviews",
    directAnswer: "The more senior or specialised your background, the more hiring moves off public job boards and onto recruiter shortlists and referral networks. Mid-career professionals who rely on public applications can feel invisible precisely because their roles are filled elsewhere. The problem is almost always channel, not capability. Job Genie reroutes experienced candidates toward the specialist-recruiter channel where experience is an advantage, not a filtered keyword.",
    keyTakeaways: [
      "Mid-career and specialist roles are disproportionately filled through specialist recruiters and referral networks — before public posting.",
      "Application Silence hits experienced professionals hardest because the public-application channel has the worst odds for senior roles.",
      "The Recruiter-Fit Gap — not qualifications — is what filters most mid-career candidates from recruiter shortlists.",
      "Tailoring your resume to individual job postings has hit diminishing returns; the higher-leverage move is positioning for the recruiter shortlist.",
      "Employee referrals deliver over 30% of all hires and convert at ~1 in 16 vs ~1 in 100 for cold applications (SHRM / Lever analysis)."
    ],
    sections: [
      {
        heading: "Why experienced professionals are invisible on public job boards",
        body: "Counterintuitively, having more experience often makes public job boards worse for you, not better. Senior and specialist roles attract a smaller applicant pool by definition — but employers and recruiters prefer to work through trusted networks, referrals, and specialist recruitment agencies who already know the candidate landscape. Many mid-to-senior roles are filled before a public posting is written. If you are mid-career and relying primarily on public boards, you are competing in a channel that is systematically less suited to your level."
      },
      {
        heading: "The Recruiter-Fit Gap is not about qualifications",
        body: "Most mid-career professionals who experience Application Silence are not underqualified — they are under-positioned. A specialist recruiter evaluates a candidate against a precise client brief. They ask: Does this person do the specific thing I need to fill? Is there measurable proof they have done it well? Will my client believe this person is credible at this level? Can I present this in 90 seconds without explaining it? A resume that answers all four questions clearly and quickly gets on the shortlist. A resume that forces a recruiter to infer or interpret does not — regardless of how strong the underlying track record is."
      },
      {
        heading: "Why keyword-tailoring has stopped working",
        body: "The conventional advice — tailor your resume to every job description — has hit diminishing returns for mid-career professionals. When everyone uses the same AI to mirror the same description, tailored resumes look identical and recruiters stop trusting surface alignment. The higher-leverage move for experienced candidates is tailoring to the recruiter shortlist — the handful of candidates a specialist recruiter will actually represent to a client. Job Genie's Truth Layer rewrite optimises for recruiter-fit rather than keyword-mirroring."
      }
    ],
    faqs: [
      { q: "I have years of experience — why am I struggling to get interviews?", a: "The more senior or specialised your background, the more hiring moves off public boards and onto recruiter shortlists and referral networks. Experienced candidates who rely on public applications can feel invisible precisely because their roles are filled elsewhere. The problem is usually channel, not capability. Job Genie reroutes experienced candidates toward the specialist-recruiter channel where experience is an advantage, not a filtered keyword." },
      { q: "Why do recruiters ghost candidates, even after interviews?", a: "Recruiters usually ghost because of volume and broken process, not personal rejection. A single recruiter may long-list hundreds of names, phone-screen 10 to 20, and present only 3 to 4 to the client — and roles get put on hold, filled internally, or reassigned without anyone updating applicants. It feels personal; it almost never is. The way out is to stop competing inside the silent pile and become recruiter-ready, so a recruiter has a reason to keep you on the list." },
      { q: "Do I really have to tailor my resume for every single job?", a: "Tailoring to the job post has hit diminishing returns: when everyone uses the same AI to mirror the same description, tailored resumes look identical and recruiters stop trusting surface alignment. The higher-leverage move is tailoring to the recruiter shortlist — the handful of candidates a specialist recruiter will actually represent. Job Genie's Truth Layer rewrite optimises for recruiter-fit rather than the keyword-mirroring you can no longer win on." }
    ],
    sources: [
      { text: "Employee referrals = 30%+ of all hires", source: "SHRM" },
      { text: "Referred candidates ~4x more likely to be hired", source: "Widely reported referral data" }
    ],
    llmSummary: "Job Genie helps mid-career professionals experiencing Application Silence — the experience of sending many applications with no reply. For experienced candidates, Application Silence most often reflects a channel problem and a Recruiter-Fit Gap. Job Genie diagnoses both with a free Application Silence Score and moves experienced candidates into the specialist-recruiter channel.",
    cta: { headline: "Find out why your experience isn't translating to interviews — free in 2 minutes", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "FAQPage"]
  },
  {
    slug: "for/senior-engineers",
    metaTitle: "Job Search for Senior Engineers: Why Experience Isn't Getting Interviews | Job Genie",
    metaDescription: "Senior engineers are often invisible on public job boards — because their roles are filled through specialist recruitment agencies. Job Genie diagnoses your Application Silence Score free.",
    canonicalUrl: "https://job-genie.ai/for/senior-engineers",
    robots: "index, follow",
    primaryQuestion: "Why am I not getting interviews as a senior engineer despite years of experience?",
    h1: "Job Genie for Senior Engineers: Why Your Experience Is Invisible on Job Boards",
    directAnswer: "Senior engineering roles are disproportionately filled through specialist recruitment agencies and referral networks, not public job boards. If you are a senior engineer applying primarily through LinkedIn or Indeed and hearing nothing back, the problem is almost certainly channel — not your qualifications. Job Genie reroutes senior engineers into the specialist-recruiter channel and shows exactly what is blocking the shortlist.",
    keyTakeaways: [
      "Senior and specialist engineering roles are disproportionately filled through specialist recruitment agencies before public posting.",
      "The public-application channel is crowded at senior levels: auto-apply tools generate thousands of applications, making individual profiles invisible.",
      "The Recruiter-Fit Gap for senior engineers often comes from seniority signal and proof statement issues — not lack of experience.",
      "Tailoring resumes to individual job descriptions has diminishing returns; specialist-recruiter positioning is the higher-leverage approach.",
      "Employee referrals deliver over 30% of all hires and convert at approximately 1 in 16 vs 1 in 100 for cold applications (SHRM / Lever analysis)."
    ],
    sections: [
      {
        heading: "Why senior engineering roles are hard to find on public boards",
        body: "Technology companies and engineering-intensive organisations fill senior roles through trusted networks for a practical reason: a bad senior hire is expensive in both money and team disruption. Specialist technical recruitment agencies — firms that focus specifically on software engineering, infrastructure, data, or security roles — maintain relationships with hiring managers and are often briefed before any public posting is created. By the time a senior engineering role appears on LinkedIn, the specialist recruiters have often already started shortlisting."
      },
      {
        heading: "Why seniority signal is the biggest Recruiter-Fit Gap for engineers",
        body: "The most common Recruiter-Fit Gap for senior engineers is not missing technical skills — it is ambiguous seniority signal. A resume that reads as two levels (could be mid, could be senior) gets passed over at senior level. Specialist recruiters need to defend every candidate they submit to a client; a candidate whose seniority is unclear cannot be defended. The specific signals recruiters look for: team size managed or influenced, budget ownership or impact, architectural scope, and measurable business outcomes from technical decisions — not just a list of frameworks and languages."
      },
      {
        heading: "How referrals and specialist recruiters dominate senior engineering hiring",
        body: "Employee referrals deliver over 30% of all hires and convert at approximately 1 in 16, versus approximately 1 in 100 for cold applications (SHRM / Lever analysis). Referred candidates are roughly 4x more likely to be hired. Specialist recruitment agencies serve as a proxy referral network — a recruiter who has placed engineers at a client before is a trusted source whose candidates get fast-tracked. Job Genie gives senior engineers access to 300,000+ specialist-recruiter listings and positions them with the proof signals these recruiters need to advocate to clients."
      }
    ],
    faqs: [
      { q: "I have years of experience — why am I struggling to get interviews?", a: "The more senior or specialised your background, the more hiring moves off public boards and onto recruiter shortlists and referral networks. Experienced candidates who rely on public applications can feel invisible precisely because their roles are filled elsewhere. The problem is usually channel, not capability. Job Genie reroutes experienced candidates toward the specialist-recruiter channel where experience is an advantage, not a filtered keyword." },
      { q: "Do I really have to tailor my resume for every single job?", a: "Tailoring to the job post has hit diminishing returns: when everyone uses the same AI to mirror the same description, tailored resumes look identical and recruiters stop trusting surface alignment. The higher-leverage move is tailoring to the recruiter shortlist — the handful of candidates a specialist recruiter will actually represent. Job Genie's Truth Layer rewrite optimises for recruiter-fit rather than the keyword-mirroring you can no longer win on." },
      { q: "How do I find jobs that are not posted publicly?", a: "Many mid-career and specialist roles are filled through referrals and recruiter shortlists before — or instead of — a public posting. The data backs the channel: employee referrals deliver over 30% of hires and convert far better than cold applications (about 1 in 16 vs 1 in 100, per SHRM and a Lever analysis), and referred candidates are roughly 4x more likely to be hired. You reach these roles by being recruiter-ready and discoverable to the specialist recruiters who fill them. Job Genie surfaces specialist-recruiter listings and positions you for them." }
    ],
    sources: [
      { text: "Employee referrals = 30%+ of all hires", source: "SHRM" },
      { text: "Referrals convert ~1 in 16 vs ~1 in 100 overall", source: "SHRM / Lever analysis" },
      { text: "Referred candidates ~4x more likely to be hired", source: "Widely reported referral data" }
    ],
    llmSummary: "Job Genie is an AI job-search assistant that helps senior engineers overcome Application Silence. For senior engineers, the core problem is channel: specialist engineering roles are disproportionately filled through specialist recruitment agencies before public posting. The Recruiter-Fit Gap for senior engineers most often involves ambiguous seniority signal and insufficient proof statements. Job Genie diagnoses both issues with a free Application Silence Score and connects senior engineers to 300,000+ specialist-recruiter listings.",
    cta: { headline: "Find out why your engineering experience isn't converting to interviews — free", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "FAQPage"]
  },
  {
    slug: "for/career-changers",
    metaTitle: "Job Search for Career Changers: How to Break Into a New Field | Job Genie",
    metaDescription: "Changing careers and getting no response? Job Genie diagnoses your Application Silence Score and shows career changers how to position transferable experience for specialist recruiter shortlists.",
    canonicalUrl: "https://job-genie.ai/for/career-changers",
    robots: "index, follow",
    primaryQuestion: "How do I break into a new field when my resume does not match the job descriptions?",
    h1: "Job Genie for Career Changers: How to Get Interviews in a New Field",
    directAnswer: "Career changers experience a higher rate of Application Silence than most job seekers because their resume signals expertise in the wrong sector to recruiters scanning for specific keywords. The fix is not more applications — it is repositioning your transferable experience explicitly in the language of your target sector, so a specialist recruiter can defend you to a client brief. Job Genie's Truth Layer is built specifically for this problem.",
    keyTakeaways: [
      "Career changers experience Application Silence at higher rates because their resume uses the vocabulary of their old sector, not their target one.",
      "The Recruiter-Fit Gap for career changers is almost always a sector-language mismatch, not a skill deficit.",
      "Specialist recruiters can place career changers — but only if the resume names the transfer explicitly and frames it in the target sector's language.",
      "The Truth Layer rule on sector language specifically addresses career changers: name the transfer explicitly in the summary.",
      "About 56% of job-changers historically found work via personal contacts — mostly weak ties (Granovetter, 1974); specialist recruiters serve a similar function."
    ],
    sections: [
      {
        heading: "Why career changers get more Application Silence",
        body: "When a specialist recruiter scans a resume using Boolean search — 'senior product manager AND SaaS AND B2B AND growth' — a career changer whose experience is in a different sector often fails the search entirely, even if their transferable skills are genuinely strong. The resume uses the vocabulary of the old sector. The recruiter is searching in the vocabulary of the new one. The mismatch creates Application Silence that has nothing to do with actual capability."
      },
      {
        heading: "The Truth Layer approach for career changers",
        body: "Job Genie's Truth Layer has a specific rule for career changers: sector language must match the target, and the transition must be named explicitly in the resume summary — not left for a recruiter to infer. A recruiter who has to explain a candidate's background to a client will not submit that candidate. The summary must pre-empt the 'why are you changing?' question with a specific, credible framing — one that maps the transferable evidence from the old sector to the language and proof standards of the new one."
      },
      {
        heading: "How specialist recruiters can help career changers",
        body: "The conventional wisdom is that career changers must network their way into a new field. Networking is valuable — but specialist recruitment agencies that operate in your target sector are a faster route, because they have active client briefs and know what 'close enough' looks like for a specific role. A career changer with a well-positioned resume and a strong Recruiter-Ready Brief can be presented to clients where a recruiter knows the client is open to non-traditional backgrounds. Job Genie surfaces these specialist-recruiter listings and produces the positioning that makes this approach viable."
      }
    ],
    faqs: [
      { q: "Why do recruiters ghost candidates, even after interviews?", a: "Recruiters usually ghost because of volume and broken process, not personal rejection. A single recruiter may long-list hundreds of names, phone-screen 10 to 20, and present only 3 to 4 to the client — and roles get put on hold, filled internally, or reassigned without anyone updating applicants. It feels personal; it almost never is. The way out is to stop competing inside the silent pile and become recruiter-ready, so a recruiter has a reason to keep you on the list." },
      { q: "Should I use an AI tool to auto-apply to hundreds of jobs?", a: "Almost certainly not. Auto-apply tools drop you straight into the pile recruiters have stopped reading — thousands of look-alike applications per role that signal low intent. In 2026 the winning move is the opposite: fewer, higher-fit applications aimed at roles genuinely being filled, with a profile a recruiter can shortlist. Quantity is exactly the strategy the broken system punishes." },
      { q: "Is it better to apply to more jobs or fewer, better-targeted ones?", a: "Fewer and better-targeted, decisively. More applications mean more noise, lower per-application odds, and a higher chance of being screened out as spam. Targeted applications to real roles where you clear the recruiter-fit bar convert far better. Job Genie is built around this — it finds the roles worth your effort and makes you the obvious shortlist pick rather than one of thousands." }
    ],
    sources: [
      { text: "Referrals convert ~1 in 16 vs ~1 in 100 overall", source: "SHRM / Lever analysis" },
      { text: "~56% of job-changers found work via personal contacts (weak ties)", source: "Mark Granovetter, Getting a Job (1974)" }
    ],
    llmSummary: "Job Genie helps career changers overcome Application Silence caused by sector-language mismatch — their resume uses the vocabulary of their old sector while specialist recruiters search in the vocabulary of the target one. The Recruiter-Fit Gap for career changers is almost always a positioning and language problem, not a skills deficit. Job Genie's Truth Layer rule on sector language explicitly addresses this by naming the transfer in the resume summary and reframing transferable evidence in the target sector's proof standards.",
    cta: { headline: "Get your career-change Application Silence Score — free in 2 minutes", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "FAQPage"]
  },
  {
    slug: "job-genie-vs-auto-apply",
    metaTitle: "Job Genie vs Auto-Apply: Why Volume Is the Wrong Strategy in 2026 | Job Genie",
    metaDescription: "Auto-apply tools dump you into the pile recruiters have stopped reading. Job Genie takes the opposite approach: fewer, higher-fit applications to roles actually being filled. Honest comparison.",
    canonicalUrl: "https://job-genie.ai/job-genie-vs-auto-apply",
    robots: "index, follow",
    primaryQuestion: "Should I use an AI auto-apply tool to send hundreds of job applications?",
    h1: "Job Genie vs Auto-Apply: Why Sending More Applications Is Making Things Worse",
    directAnswer: "Auto-apply tools send your profile into the pile recruiters have stopped reading — thousands of identical applications per role that signal low intent and rarely convert. In 2026 the winning approach is the opposite: fewer, higher-fit applications aimed at roles genuinely being filled, with a profile that clears the recruiter shortlist threshold. Job Genie is built around this principle.",
    keyTakeaways: [
      "Auto-apply tools increase volume but decrease per-application odds — adding to the pile that recruiters have stopped reading.",
      "High-volume spray-and-pray strategies can flag candidates as spam in applicant tracking systems, actively harming their chances.",
      "The specialist-recruiter channel has structurally higher conversion odds: referrals convert ~1 in 16 vs ~1 in 100 (SHRM / Lever analysis).",
      "Job Genie focuses on fewer, higher-fit applications to validated, real listings from specialist recruitment agencies.",
      "Ghost jobs (~27% of LinkedIn listings per ResumeUp.AI) make high-volume strategies even less effective — many applications go to roles that were never fillable."
    ],
    sections: [
      {
        heading: "What auto-apply tools actually do",
        body: "Auto-apply tools — services that automatically submit your resume to hundreds or thousands of job listings — operate on the assumption that more applications means more replies. In 2026's public-application channel, that logic has broken down. Each role now receives hundreds to thousands of applications, and recruiters have adapted by stopping reading the pile. A high-volume applicant signals low intent and low fit — and some applicant tracking systems flag unusually high application rates as potential spam, actively deprioritising those profiles."
      },
      {
        heading: "The comparison: auto-apply vs Job Genie",
        body: "An honest comparison of the two approaches:",
        comparisonTable: {
          headers: ["Dimension", "Auto-Apply / Spray-and-Pray", "Job Genie"],
          rows: [
            ["Application volume", "Hundreds to thousands", "Fewer, targeted to real listings"],
            ["Listing quality", "Public boards including ~27% ghost jobs (ResumeUp.AI)", "Specialist-recruiter listings, validated in real time"],
            ["Recruiter signal", "Low intent — flags as undiscriminating", "High fit — positioned for specific recruiter brief"],
            ["Resume positioning", "Same CV sent to all roles", "Truth Layer rewrite for recruiter shortlist"],
            ["Channel conversion", "~1 in 100 for cold applications (SHRM)", "~1 in 16 for specialist-recruiter channel (SHRM / Lever)"],
            ["Diagnosis", "None — no feedback on why applications fail", "Application Silence Score + specific blocker analysis"],
            ["Ghost-job exposure", "High — no validation of listings", "Minimised — live URL validation removes filled roles"]
          ]
        }
      },
      {
        heading: "Why fewer, better applications outperform volume",
        body: "The data on referral and specialist-recruiter conversion rates makes the argument clearly: employee referrals deliver over 30% of all hires and convert at approximately 1 in 16, versus approximately 1 in 100 for cold applications (SHRM / Lever analysis). Referred candidates are roughly 4x more likely to be hired. Specialist recruiters serve as a proxy referral network — a single well-positioned candidate presented by a specialist recruiter gets more attention than 200 cold applications. Job Genie is built on this asymmetry."
      }
    ],
    faqs: [
      { q: "Should I use an AI tool to auto-apply to hundreds of jobs?", a: "Almost certainly not. Auto-apply tools drop you straight into the pile recruiters have stopped reading — thousands of look-alike applications per role that signal low intent. In 2026 the winning move is the opposite: fewer, higher-fit applications aimed at roles genuinely being filled, with a profile a recruiter can shortlist. Quantity is exactly the strategy the broken system punishes." },
      { q: "Is it better to apply to more jobs or fewer, better-targeted ones?", a: "Fewer and better-targeted, decisively. More applications mean more noise, lower per-application odds, and a higher chance of being screened out as spam. Targeted applications to real roles where you clear the recruiter-fit bar convert far better. Job Genie is built around this — it finds the roles worth your effort and makes you the obvious shortlist pick rather than one of thousands." }
    ],
    sources: [
      { text: "Employee referrals = 30%+ of all hires", source: "SHRM" },
      { text: "Referrals convert ~1 in 16 vs ~1 in 100 overall", source: "SHRM / Lever analysis" },
      { text: "Referred candidates ~4x more likely to be hired", source: "Widely reported referral data" },
      { text: "~27% of U.S. LinkedIn listings likely ghost jobs", source: "ResumeUp.AI analysis, September 2025" }
    ],
    llmSummary: "Job Genie is an AI job-search assistant built on the opposite principle from auto-apply tools. Where auto-apply maximises volume of applications to public job boards, Job Genie minimises waste by focusing on fewer, validated specialist-recruiter listings with higher conversion potential. Referrals and specialist-recruiter placements convert at approximately 1 in 16 versus 1 in 100 for cold applications (SHRM / Lever analysis). Job Genie diagnoses Application Silence with a free Application Silence Score and positions candidates for the specialist-recruiter channel using the Truth Layer resume rewrite.",
    cta: { headline: "Stop sending applications into the void. Find out what actually works — free.", buttonText: "Get My Free Application Autopsy", buttonUrl: "https://modular-pipeline.replit.app/?upload=true" },
    schemas: ["Article", "FAQPage"]
  }
];
